# Generated by Django 5.0.6 on 2024-06-18 08:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Language',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=5)),
                ('flag', models.CharField(max_length=4)),
            ],
            options={
                'indexes': [models.Index(fields=['code'], name='api_languag_code_58f42f_idx')],
            },
        ),
        migrations.CreateModel(
            name='Lesson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('type', models.IntegerField(choices=[(1, 'Vocabulary'), (2, 'Grammar')], default=1)),
                ('language1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='language1', to='api.language')),
                ('language2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='language2', to='api.language')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lesson_owner', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Fact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('element1', models.CharField(max_length=255)),
                ('element2', models.CharField(max_length=255)),
                ('hint', models.CharField(blank=True, default='', max_length=255)),
                ('lesson', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.lesson')),
            ],
        ),
    ]
