# Generated by Django 5.0.6 on 2024-10-29 03:59

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_fact_id_alter_lesson_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='lesson',
            name='is_deleted',
            field=models.BooleanField(default=False, editable=False),
        ),
        migrations.AddField(
            model_name='lesson',
            name='status',
            field=models.IntegerField(choices=[(0, 'Private'), (1, 'Public')], default=0),
        ),
        migrations.AlterField(
            model_name='fact',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
    ]
