# Generated by Django 5.0.11 on 2025-08-31 03:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_lesson_is_deleted_lesson_status_alter_fact_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='fact',
            name='is_deleted',
            field=models.BooleanField(default=False, editable=False),
        ),
        migrations.AddField(
            model_name='fact',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
