services:
  server:
    build:
      context: .
      target: builder
    container_name: lingolessons
    ports:
      - '8000:8000'
    env_file:
      - ./env.dev
    depends_on:
      - db

  db:
      image: postgres:15
      container_name: lingolessons-db
      volumes:
        - postgres_data:/var/lib/postgresql/data/
      env_file:
        - ./env.dev.db

volumes:
  postgres_data:
