[package]
name = "shared"
version = "0.1.0"
edition = "2021"

[dependencies]
async-compat = "0.2.4"
#async-std = { version = "1", features = ["attributes", "tokio1"] }
#uniffi.workspace = true
serde = "1.0.210"
thiserror = "1.0.56"
openssl = { version = "0.10", features = ["vendored"] }
tokio = { version = "1", features = ["full"] }
reqwest = { version = "0.12", features = ["json"] }
rusqlite = { version = "0.31.0", features = ["bundled"] }
rusqlite_migration = { version = "1.2.0", features = ["from-directory"] }
lazy_static = "1.5.0"
include_dir = { version = "0.7.4" }
concat-string = "1.0.1"
uniffi = { version = "0.28.1", features = ["tokio"] }
env_logger = "0.11.5"

[target.'cfg(target_os = "android")'.dependencies]
android_logger = "0.14.1"

[build-dependencies]

[lib]
name = "shared"
path = "src/lib.rs"
crate-type = ["cdylib", "staticlib", "lib"]

[features]
#tokio = ["uniffi_core/tokio"]
#default = []
#from-directory = ["dep:include_dir"]

#[target.x86_64-linux-android]
#linker = "x86_64-linux-android30-clang"
#ar = "llvm-ar"
#rustflags = [
#    "-L$ANDROID_NDK_HOME/toolchains/llvm/prebuilt/linux-x86_64/lib/clang/18/lib/linux/",
#    "-lstatic=clang_rt.builtins-x86_64-android"
#]
#
#[target.aarch64-linux-android]
#linker = "aarch64-linux-android30-clang"
#ar = "llvm-ar"
