name: Android CI

on:
  push:
    paths:
      - "client/**"
      - '.github/workflows/android.yml'
    branches: [ "master" ]
  pull_request:
    paths:
      - "client/**"
      - '.github/workflows/**'
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./client
        
    steps:
    - uses: actions/checkout@v4
    - name: set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: gradle

    - name: Grant execute permission for gradlew
      run: chmod +x gradlew

    - name: Run Unit tests
      run: ./gradlew testDebugUnitTest

    - name: Publish test report
      uses: mikepenz/action-junit-report@v4
      with:
        check_name: 'Android Test Report'
        token: ${{ secrets.GITHUB_TOKEN }}
        report_paths: '**/build/test-results/testDebugUnitTest/TEST-*.xml'

    - name: Generate kover coverage report
      run: ./gradlew koverXmlReportDebug

    - name: Add coverage report
      id: kover
      uses: mi-kas/kover-report@v1
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        path: 'client/composeApp/build/reports/kover/reportDebug.xml'
        coverage-counter-type: LINE

    - name: Build with Gradle
      if: false
      working-directory: ./client
      run: ./gradlew build
