name: Android CI

on:
  push:
    paths:
      - "client/**"
      - '.github/workflows/**'
    branches: [ "master" ]
  pull_request:
    paths:
      - "client/**"
      - '.github/workflows/**'
    branches: [ "master" ]


jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: gradle

    - name: Grant execute permission for gradlew
      run: chmod +x ./client/gradlew
    - name: Build with Gradle
      working-directory: ./client
      run: ./gradlew build
