name: Django CI

on:
  push:
    paths:
      - "server/**"
      - '.github/workflows/django.yml'
    branches: [ "master" ]
  pull_request:
    paths:
      - "server/**"
      - '.github/workflows/django.yml'
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./server

    steps:
    - uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version-file: "pyproject.toml"

    - name: Install uv
      uses: astral-sh/setup-uv@v6

    - name: Install Dependencies
      run: uv sync --locked --all-extras --dev

    - name: Run Tests
      run: |
        python manage.py test --verbosity 2
