name: iOS CI

on:
  push:
    paths:
      - "client/**"
      - '.github/workflows/ios.yml'
    branches: [ "master" ]
  pull_request:
    paths:
      - "client/**"
      - '.github/workflows/ios.yml'
    branches: [ "master" ]

jobs:
  build:
    name: Build and Test default scheme using any available iPhone simulator
    runs-on: macos-latest
    defaults:
      run:
        working-directory: ./client/iosApp

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up cocoapods
        uses: maxim-lobanov/setup-cocoapods@v1
        with:
          version: latest

      - name: Install Dependencies
        run: pod install --verbose

      - run: xcodebuild build -workspace iosApp/iosApp.xcworkspace -configuration Debug -scheme iosApp -sdk iphoneos -destination name='iPhone 14' CODE_SIGNING_ALLOWED=NO -verbose
